import json
import sqlite3
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def connect(database_path: str) -> sqlite3.Connection:
    connection = sqlite3.connect(str(Path(database_path)))
    connection.row_factory = sqlite3.Row
    return connection


def quote_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def normalize_table_sql(sql: str) -> str:
    return (
        sql.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
        .replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        .replace("DATETIME", "TIMESTAMP")
    )


def normalize_index_sql(sql: str) -> str:
    if sql.startswith("CREATE UNIQUE INDEX "):
        return sql.replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1)
    return sql.replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1)


def get_tables(connection: sqlite3.Connection):
    return connection.execute(
        "SELECT name, sql, rowid FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    ).fetchall()


def build_select_sql(table_name: str) -> str:
    if table_name == "categories":
        return 'SELECT * FROM "categories" ORDER BY COALESCE(level, 0), category_id'
    return f'SELECT * FROM "{table_name}"'


def get_dependency_order(connection: sqlite3.Connection):
    tables = get_tables(connection)
    table_names = [row["name"] for row in tables]
    table_set = set(table_names)
    dependency_map = {}

    for table_name in table_names:
        dependencies = [
            row["table"]
            for row in connection.execute(f'PRAGMA foreign_key_list("{table_name}")').fetchall()
            if row["table"] in table_set and row["table"] != table_name
        ]
        dependency_map[table_name] = dependencies

    ordered = []
    visited = set()
    visiting = set()

    def visit(table_name: str):
        if table_name in visited or table_name in visiting:
            return
        visiting.add(table_name)
        for dependency in dependency_map.get(table_name, []):
            visit(dependency)
        visiting.remove(table_name)
        visited.add(table_name)
        ordered.append(table_name)

    for table_name in table_names:
        visit(table_name)

    return ordered


def print_counts(connection: sqlite3.Connection):
    payload = []
    for row in connection.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall():
        name = row["name"]
        count = connection.execute(f'SELECT COUNT(*) AS count FROM "{name}"').fetchone()["count"]
        payload.append({"name": name, "count": count})
    print(json.dumps(payload, indent=2, ensure_ascii=False))


def print_metadata(connection: sqlite3.Connection):
    ordered_names = get_dependency_order(connection)
    payload = []

    for table_name in ordered_names:
        table_info = connection.execute(f'PRAGMA table_info("{table_name}")').fetchall()
        count = connection.execute(f'SELECT COUNT(*) AS count FROM "{table_name}"').fetchone()["count"]
        primary_key = None

        if len(table_info) > 0:
            primary_columns = sorted(
                [row for row in table_info if int(row["pk"] or 0) > 0],
                key=lambda row: int(row["pk"] or 0),
            )
            if len(primary_columns) == 1:
                primary_key = {
                    "column": primary_columns[0]["name"],
                    "type": primary_columns[0]["type"] or "",
                }

        payload.append(
            {
                "name": table_name,
                "count": count,
                "primary_key": primary_key,
            }
        )

    print(json.dumps(payload, indent=2, ensure_ascii=False))


def print_schema(connection: sqlite3.Connection):
    ordered_names = get_dependency_order(connection)
    by_name = {row["name"]: row["sql"] for row in get_tables(connection)}
    indexes = connection.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'index' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY rowid"
    ).fetchall()

    statements = ["-- Generated from local SQLite schema", "", "BEGIN;", ""]
    for name in ordered_names:
        statements.append(normalize_table_sql(by_name[name]).rstrip(";") + ";")
        statements.append("")
    for row in indexes:
        statements.append(normalize_index_sql(row["sql"]).rstrip(";") + ";")
        statements.append("")
    statements.append("COMMIT;")
    print("\n".join(statements))


def print_order(connection: sqlite3.Connection):
    print(json.dumps(get_dependency_order(connection), indent=2, ensure_ascii=False))


def print_group(connection: sqlite3.Connection, table_names: list[str]):
    statements = []
    for table_name in table_names:
      columns = [row["name"] for row in connection.execute(f'PRAGMA table_info("{table_name}")').fetchall()]
      rows = connection.execute(build_select_sql(table_name)).fetchall()
      if not columns or not rows:
          continue
      column_list = ", ".join(f'"{column}"' for column in columns)
      values = ",\n".join(
          "(" + ", ".join(quote_literal(row[column]) for column in columns) + ")"
          for row in rows
      )
      statements.append(f'INSERT INTO "{table_name}" ({column_list}) VALUES\n{values};')
    print("\n\n".join(statements))


def print_batch(connection: sqlite3.Connection, table_name: str, offset: int, limit: int):
    columns = [row["name"] for row in connection.execute(f'PRAGMA table_info("{table_name}")').fetchall()]
    rows = connection.execute(
        build_select_sql(table_name) + " LIMIT ? OFFSET ?",
        (limit, offset),
    ).fetchall()
    if not columns or not rows:
        print("")
        return
    column_list = ", ".join(f'"{column}"' for column in columns)
    values = ",\n".join(
        "(" + ", ".join(quote_literal(row[column]) for column in columns) + ")"
        for row in rows
    )
    print(f'INSERT INTO "{table_name}" ({column_list}) VALUES\n{values};')


def print_dump(connection: sqlite3.Connection, batch_size: int):
    ordered_names = get_dependency_order(connection)
    statements = [
        "-- Generated from local SQLite data",
        "",
        "BEGIN;",
        "",
        "TRUNCATE TABLE",
        "  " + ",\n  ".join(f'"{table_name}"' for table_name in reversed(ordered_names)),
        "RESTART IDENTITY CASCADE;",
        "",
    ]

    for table_name in ordered_names:
        table_info = connection.execute(f'PRAGMA table_info("{table_name}")').fetchall()
        columns = [row["name"] for row in table_info]
        if not columns:
            continue

        total_rows = connection.execute(f'SELECT COUNT(*) AS count FROM "{table_name}"').fetchone()["count"]
        if total_rows == 0:
            continue

        column_list = ", ".join(f'"{column}"' for column in columns)
        for offset in range(0, total_rows, batch_size):
            rows = connection.execute(
                build_select_sql(table_name) + " LIMIT ? OFFSET ?",
                (batch_size, offset),
            ).fetchall()
            values = ",\n".join(
                "(" + ", ".join(quote_literal(row[column]) for column in columns) + ")"
                for row in rows
            )
            statements.append(f'INSERT INTO "{table_name}" ({column_list}) VALUES\n{values};')
            statements.append("")

        primary_columns = sorted(
            [row for row in table_info if int(row["pk"] or 0) > 0],
            key=lambda row: int(row["pk"] or 0),
        )
        if len(primary_columns) == 1 and "INT" in str(primary_columns[0]["type"] or "").upper():
            primary_key = primary_columns[0]["name"]
            statements.append(
                f"""SELECT setval(
  pg_get_serial_sequence('"{table_name}"', '{primary_key}'),
  MAX("{primary_key}"),
  TRUE
) FROM "{table_name}" HAVING COUNT(*) > 0;"""
            )
            statements.append("")

    statements.append("COMMIT;")
    print("\n".join(statements))


def main():
    if len(sys.argv) < 3:
        print("Usage: python legacy/sqlite-migration/sqlite_to_postgres.py <database-path> <counts|metadata|schema|order|group|batch|dump> [...]")
        raise SystemExit(1)

    database_path = sys.argv[1]
    mode = sys.argv[2]
    connection = connect(database_path)

    if mode == "counts":
        print_counts(connection)
        return
    if mode == "metadata":
        print_metadata(connection)
        return
    if mode == "schema":
        print_schema(connection)
        return
    if mode == "order":
        print_order(connection)
        return
    if mode == "group":
        if len(sys.argv) < 4:
            raise SystemExit("Usage: ... group <table1,table2,...>")
        print_group(connection, [value.strip() for value in sys.argv[3].split(",") if value.strip()])
        return
    if mode == "batch":
        if len(sys.argv) < 6:
            raise SystemExit("Usage: ... batch <table> <offset> <limit>")
        print_batch(connection, sys.argv[3], int(sys.argv[4]), int(sys.argv[5]))
        return
    if mode == "dump":
        batch_size = int(sys.argv[3]) if len(sys.argv) >= 4 else 500
        print_dump(connection, batch_size)
        return

    raise SystemExit(f"Unknown mode: {mode}")


if __name__ == "__main__":
    main()
