import { DEMO_PRODUCT_SEEDS, deriveDemoSalePrice } from "./demo-product-seeds";
import { ChannelCostResult, Product } from "./types";

export const DEMO_PRODUCTS: Product[] = DEMO_PRODUCT_SEEDS.map((seed, index) => ({
  id: index + 1,
  name: seed.name,
  sku: seed.sku,
  barcode: seed.barcode,
  image_url: seed.imageUrl,
  category_name: seed.categoryPath.split(" > ").at(-1) ?? seed.categoryPath,
  category_path: seed.categoryPath,
  description: seed.description,
  cost: seed.cost,
  packaging_cost: seed.packagingCost,
  desi: seed.desi,
  sale_price: deriveDemoSalePrice(seed.cost, seed.packagingCost),
  active_channels: seed.activeChannels,
  status: seed.status,
  status_label: seed.status === "active" ? "Aktif" : seed.status === "draft" ? "Taslak" : "Pasif",
}));

/**
 * Fallback channel results for the first demo product.
 * Kept in the same pricing band as the live database so demo/offline views stay consistent.
 */
export const DEMO_CHANNEL_RESULTS: ChannelCostResult[] = [
  {
    channel_name: "Trendyol Normal",
    sale_price: deriveDemoSalePrice(420, 20),
    product_cost: 420,
    packaging_cost: 20,
    shipping_cost: 95.12,
    commission_cost: 112.35,
    platform_fee_cost: 13.19,
    payment_gateway_cost: 0,
    traffic_ad_cost: 0,
    unit_ad_cost: 0,
    unit_fixed_cost: 0,
    expected_return_cost: 0,
    total_unit_cost: 660.66,
    net_profit: 1249.34,
    profit_margin_percent: 65.41,
    output_vat: 0,
    input_vat: 0,
    estimated_vat_payable: 0,
    is_fallback: true,
  },
  {
    channel_name: "Hepsiburada",
    sale_price: deriveDemoSalePrice(420, 20),
    product_cost: 420,
    packaging_cost: 20,
    shipping_cost: 94.86,
    commission_cost: 112.35,
    platform_fee_cost: 18.59,
    payment_gateway_cost: 0,
    traffic_ad_cost: 0,
    unit_ad_cost: 0,
    unit_fixed_cost: 0,
    expected_return_cost: 0,
    total_unit_cost: 665.80,
    net_profit: 1244.20,
    profit_margin_percent: 65.14,
    output_vat: 0,
    input_vat: 0,
    estimated_vat_payable: 0,
    is_fallback: true,
  },
  {
    channel_name: "Kendi Websitem",
    sale_price: deriveDemoSalePrice(420, 20),
    product_cost: 420,
    packaging_cost: 20,
    shipping_cost: 95.00,
    commission_cost: 0,
    platform_fee_cost: 0,
    payment_gateway_cost: 26.39,
    traffic_ad_cost: 80,
    unit_ad_cost: 0,
    unit_fixed_cost: 0,
    expected_return_cost: 0,
    total_unit_cost: 641.39,
    net_profit: 1268.61,
    profit_margin_percent: 66.42,
    gross_net_profit_without_traffic: 1348.61,
    gross_margin_without_traffic: 70.61,
    output_vat: 0,
    input_vat: 0,
    estimated_vat_payable: 0,
    is_fallback: true,
  }
];
