BEGIN;

DROP TABLE IF EXISTS public.uploaded_reports CASCADE;
DROP TABLE IF EXISTS public.report_column_mappings CASCADE;
DROP TABLE IF EXISTS public.normalized_ad_rows CASCADE;
DROP TABLE IF EXISTS public.analysis_settings CASCADE;
DROP TABLE IF EXISTS public.analysis_results CASCADE;
DROP TABLE IF EXISTS public.recommendations CASCADE;
DROP TABLE IF EXISTS public.llm_outputs CASCADE;
DROP TABLE IF EXISTS public.organizations CASCADE;
DROP TABLE IF EXISTS public.organization_members CASCADE;
DROP TABLE IF EXISTS public.shipping_tariffs CASCADE;
DROP TABLE IF EXISTS public.price_optimization_runs CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.inventory_daily CASCADE;
DROP TABLE IF EXISTS public.demand_forecasts CASCADE;
DROP TABLE IF EXISTS public.seo_generations CASCADE;
DROP TABLE IF EXISTS public.seo_audits CASCADE;
DROP TABLE IF EXISTS public.seo_audit_issues CASCADE;
DROP TABLE IF EXISTS public.seo_keyword_research CASCADE;
DROP TABLE IF EXISTS public.seo_ai_recommendations CASCADE;
DROP TABLE IF EXISTS public.marketplace_credentials CASCADE;
DROP TABLE IF EXISTS public.data_center_sync_runs CASCADE;
DROP TABLE IF EXISTS public.campaign_profit_metrics CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.manual_ad_campaigns CASCADE;
DROP TABLE IF EXISTS public.manual_ad_chat_messages CASCADE;
DROP TABLE IF EXISTS public.manual_ad_ai_reports CASCADE;
DROP TABLE IF EXISTS public.product_channel_seo_contents CASCADE;
DROP TABLE IF EXISTS public.product_channel_seo_jobs CASCADE;
DROP TABLE IF EXISTS public.profit_pricing_runs CASCADE;
DROP TABLE IF EXISTS public.store_expenses CASCADE;
DROP TABLE IF EXISTS public.cost_results CASCADE;

COMMIT;
